version: '3.8'
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env

  backend:
    build: .
    restart: unless-stopped
    ports:
      - "5500:5500"
    env_file: .env
