version: '3.8'
services:
  db:
    image: postgres
    container_name: webshop-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env

  backend:
    build: .
    container_name: webshop-backend
    restart: unless-stopped
    ports:
      - "5500:5500"
    env_file: .env

networks:
  default:
    external:
      name: caddy
